name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: read code
        uses: actions/checkout@v4

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: build and push hexa-fe
        run: docker build -t suibianwanwan333/hexa-fe:v1.0.0 -f ./fe/Dockerfile ../ && docker push suibianwanwan333/hexa-fe:v1.0.0

      - name: build and push hexa-be
        run: docker build -t suibianwanwan333/hexa-be:v1.0.0 -f ./be/Dockerfile ../ && docker push suibianwanwan333/hexa-be:v1.0.0

      - name: build and push hexa-cli
        run: docker build -t suibianwanwan333/hexa-cli:v1.0.0 -f ./cli/Dockerfile ../ && docker push suibianwanwan333/hexa-cli:v1.0.0